### ISSUE TITLE
Robot jumps around when mapping with YDLIDAR TG30

### ISSUE THREAD

**Issue by ghost** [SteveMacenski/slam_toolbox#617]
**Required Info:**

- Operating System:
  - Ubuntu 22.04 (on WSL2) 
- Installation type:
  - from source
- ROS Version
  - ROS2 Humble
- Version or commit hash:
  - branch: ros2
  - commit hash: b08d182553c07cfe3cd2c3aca04493dcd52a60f0
- Laser unit:
  - RPLiDAR S2
  - YDLIDAR TG30
  
#### Steps to reproduce issue
- run `online_async_launch` in mapping mode with this [robot](https://robots.ros.org/megarover-ver.3.0/)
- tested with RPLiDAR S2 and YDLIDAR TG30
- YDLIDAR driver used: https://github.com/YDLIDAR/ydlidar_ros2_driver
- RPLIDAR driver used: https://github.com/Slamtec/sllidar_ros2
- my `mapper_params_online_async.yaml`
  ```yaml
  slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    mode: mapping #localization

    # if you'd like to immediately start continuing a map at a given pose
    # or at the dock, but they are mutually exclusive, if pose is given
    # will use pose
    #map_file_name: test_steve
    # map_start_pose: [0.0, 0.0, 0.0]
    #map_start_at_dock: true

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02 #if 0 never publishes odometry
    map_update_interval: 3.0
    resolution: 0.05
    max_laser_range: 30.0 # default: 20.0 #for rastering images
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000 # program needs a larger stack size to serialize large maps
    enable_interactive_mode: true

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1  
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true 
    loop_match_minimum_chain_size: 10           
    loop_match_maximum_variance_coarse: 3.0  
    loop_match_minimum_response_coarse: 0.35    
    loop_match_minimum_response_fine: 0.45

    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1 

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 0.5      
    angle_variance_penalty: 1.0    

    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0349        
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
  ```
  

#### Expected behavior
- map created without robot jumping around

#### Actual behavior
- **RPLiDAR S2**: some slight deviation noticed, but map looks decent
  gif:  
![rplidar-issue-compressed](https://github.com/SteveMacenski/slam_toolbox/assets/92380000/48cd46c8-cc47-4c88-b178-9dec1fa3fec2)

  terminal log: 
```
[INFO] [launch]: All log files can be found below /home/wsl-2204/.ros/log/2023-06-20-11-40-49-441648-MSI-25233
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [joint_state_publisher-1]: process started with pid [25243]
[INFO] [robot_state_publisher-2]: process started with pid [25245]
[INFO] [rviz2-3]: process started with pid [25247]
[INFO] [pub_odom-4]: process started with pid [25249]
[INFO] [sllidar_node-5]: process started with pid [25251]
[INFO] [async_slam_toolbox_node-6]: process started with pid [25253]
[sllidar_node-5] [INFO] [1687228849.795232957] [sllidar_node_name]: SLLidar running on ROS2 package SLLidar.ROS2 SDK Version:1.0.1, SLLIDAR SDK Version:2.0.0
[async_slam_toolbox_node-6] [INFO] [1687228849.812708364] [slam_toolbox]: Node using stack size 40000000
[sllidar_node-5] [INFO] [1687228849.859633507] [sllidar_node_name]: SLLidar S/N: 95DAE3F5--------------------
[sllidar_node-5] [INFO] [1687228849.859702359] [sllidar_node_name]: Firmware Ver: 1.01
[sllidar_node-5] [INFO] [1687228849.859714368] [sllidar_node_name]: Hardware Rev: 18
[robot_state_publisher-2] [INFO] [1687228849.888838138] [robot_state_publisher]: got segment back_lrf_link
[robot_state_publisher-2] [INFO] [1687228849.888980739] [robot_state_publisher]: got segment base_footprint
[robot_state_publisher-2] [INFO] [1687228849.888990368] [robot_state_publisher]: got segment base_link
[robot_state_publisher-2] [INFO] [1687228849.888995625] [robot_state_publisher]: got segment front_lrf_link
[robot_state_publisher-2] [INFO] [1687228849.889000375] [robot_state_publisher]: got segment left_wheel_1
[robot_state_publisher-2] [INFO] [1687228849.889005198] [robot_state_publisher]: got segment right_wheel_1
[sllidar_node-5] [INFO] [1687228849.911486157] [sllidar_node_name]: SLLidar health status : 0
[sllidar_node-5] [INFO] [1687228849.911614695] [sllidar_node_name]: SLLidar health status : OK.
[rviz2-3] [INFO] [1687228849.980900764] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-3] [INFO] [1687228849.982824186] [rviz2]: OpenGl version: 4.5 (GLSL 4.5)
[async_slam_toolbox_node-6] [INFO] [1687228849.997490778] [slam_toolbox]: Using solver plugin solver_plugins::CeresSolver
[async_slam_toolbox_node-6] [INFO] [1687228849.997752344] [slam_toolbox]: CeresSolver: Using SCHUR_JACOBI preconditioner.
[rviz2-3] [INFO] [1687228850.025327029] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-3] [WARN] [1687228850.146488790] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[sllidar_node-5] [INFO] [1687228850.156996224] [sllidar_node_name]: current scan mode: DenseBoost, sample rate: 32 Khz, max_distance: 30.0 m, scan frequency:10.0 Hz,
[rviz2-3] [WARN] [1687228850.162566501] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[joint_state_publisher-1] [INFO] [1687228850.351182072] [joint_state_publisher]: Waiting for robot_description to be published on the robot_description topic...
[async_slam_toolbox_node-6] Registering sensor: [Custom Described Lidar]
[rviz2-3] [INFO] [1687228862.127213078] [rviz2]: Trying to create a map of size 246 x 64 using 1 swatches
[rviz2-3] [ERROR] [1687228862.223013719] [rviz2]: Vertex Program:rviz/glsl120/indexed_8bit_image.vert Fragment Program:rviz/glsl120/indexed_8bit_image.frag GLSL link result :
[rviz2-3] active samplers with a different type refer to the same texture image unit
[rviz2-3] [ERROR] [1687228862.234059596] [rviz2]: Lookup would require extrapolation into the future.  Requested time 1687228862.163658 but the latest data is at time 1687228862.149275, when looking up transform from frame [front_lrf_link] to frame [odom]
[rviz2-3] [INFO] [1687228865.126506964] [rviz2]: Trying to create a map of size 248 x 98 using 1 swatches
[rviz2-3] [ERROR] [1687228866.424871472] [rviz2]: Lookup would require extrapolation into the future.  Requested time 1687228866.361249 but the latest data is at time 1687228866.349907, when looking up transform from frame [front_lrf_link] to frame [odom]
[rviz2-3] [INFO] [1687228868.127189625] [rviz2]: Trying to create a map of size 249 x 98 using 1 swatches
[rviz2-3] [INFO] [1687228871.124913161] [rviz2]: Trying to create a map of size 249 x 99 using 1 swatches
[rviz2-3] [INFO] [1687228880.125281700] [rviz2]: Trying to create a map of size 249 x 100 using 1 swatches
[rviz2-3] [INFO] [1687228886.125693151] [rviz2]: Trying to create a map of size 249 x 145 using 1 swatches
[rviz2-3] [INFO] [1687228889.126158525] [rviz2]: Trying to create a map of size 250 x 154 using 1 swatches
  ```
- **YDLIDAR TG30**: robot jumps around when mapping, producing bad map, disabling `use_scan_matching` fixes the issue, but 
  gif: 
![ydlidar-issue-compressed](https://github.com/SteveMacenski/slam_toolbox/assets/92380000/e060286f-79a3-4a27-806e-65454fd6ca1a)

  terminal log:
```
  [INFO] [launch]: All log files can be found below /home/wsl-2204/.ros/log/2023-06-20-12-06-23-844572-MSI-8296
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [ydlidar_ros2_driver_node-5]: process started with pid [8316]
[INFO] [joint_state_publisher-1]: process started with pid [8308]
[INFO] [robot_state_publisher-2]: process started with pid [8310]
[INFO] [rviz2-3]: process started with pid [8312]
[INFO] [pub_odom-4]: process started with pid [8314]
[INFO] [async_slam_toolbox_node-6]: process started with pid [8318]
[ydlidar_ros2_driver_node-5] [INFO] [1687230384.326249623] [ydlidar_ros2_driver_node]: [YDLIDAR INFO] Current ROS Driver Version: 1.0.1
[ydlidar_ros2_driver_node-5]
[ydlidar_ros2_driver_node-5] [YDLIDAR] SDK initializing
[ydlidar_ros2_driver_node-5] [YDLIDAR] SDK has been initialized
[ydlidar_ros2_driver_node-5] [YDLIDAR] SDK Version: 1.1.13
[async_slam_toolbox_node-6] [INFO] [1687230384.353190702] [slam_toolbox]: Node using stack size 40000000
[robot_state_publisher-2] [INFO] [1687230384.430338995] [robot_state_publisher]: got segment back_lrf_link
[robot_state_publisher-2] [INFO] [1687230384.430481438] [robot_state_publisher]: got segment base_footprint
[robot_state_publisher-2] [INFO] [1687230384.430490814] [robot_state_publisher]: got segment base_link
[robot_state_publisher-2] [INFO] [1687230384.430496287] [robot_state_publisher]: got segment front_lrf_link
[robot_state_publisher-2] [INFO] [1687230384.430501113] [robot_state_publisher]: got segment left_wheel_1
[robot_state_publisher-2] [INFO] [1687230384.430505883] [robot_state_publisher]: got segment right_wheel_1
[ydlidar_ros2_driver_node-5] [YDLIDAR] Lidar successfully connected /dev/ttyUSB1[512000]
[async_slam_toolbox_node-6] [INFO] [1687230384.588759250] [slam_toolbox]: Using solver plugin solver_plugins::CeresSolver
[async_slam_toolbox_node-6] [INFO] [1687230384.589998383] [slam_toolbox]: CeresSolver: Using SCHUR_JACOBI preconditioner.
[rviz2-3] [INFO] [1687230384.601235830] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-3] [INFO] [1687230384.601480616] [rviz2]: OpenGl version: 4.5 (GLSL 4.5)
[rviz2-3] [INFO] [1687230384.658168681] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-3] [WARN] [1687230384.802441221] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[rviz2-3] [WARN] [1687230384.816035464] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[joint_state_publisher-1] [INFO] [1687230384.966106455] [joint_state_publisher]: Waiting for robot_description to be published on the robot_description topic...
[ydlidar_ros2_driver_node-5] [YDLIDAR] Lidar running correctly! The health status: good
[ydlidar_ros2_driver_node-5] [YDLIDAR] Device info
[ydlidar_ros2_driver_node-5] Firmware version: 2.1
[ydlidar_ros2_driver_node-5] Hardware version: 1
[ydlidar_ros2_driver_node-5] Model: TG30
[ydlidar_ros2_driver_node-5] Serial: 20220105--------
[ydlidar_ros2_driver_node-5] [YDLIDAR] Get origin sample rate code: 20
[ydlidar_ros2_driver_node-5] [YDLIDAR] Get sample rate: 20.00K
[ydlidar_ros2_driver_node-5] [YDLIDAR] Current scan frequency: 10.00Hz
[ydlidar_ros2_driver_node-5] [YDLIDAR] Successfully obtained the corrected offset angle[-4.250000] from the lidar[20220105--------]
[ydlidar_ros2_driver_node-5] [YDLIDAR] Lidar init success, Elapsed time 767 ms
[ydlidar_ros2_driver_node-5] [YDLIDAR] Create thread 0x18900640
[ydlidar_ros2_driver_node-5] [YDLIDAR] Successed to start scan mode, Elapsed time 1069 ms
[ydlidar_ros2_driver_node-5] timeout count: 1
[ydlidar_ros2_driver_node-5] [YDLIDAR] Fixed Size: 2020
[ydlidar_ros2_driver_node-5] [YDLIDAR] Sample Rate: 20.00K
[ydlidar_ros2_driver_node-5] [YDLIDAR] Successed to check the lidar, Elapsed time 682 ms
[ydlidar_ros2_driver_node-5] [YDLIDAR] Current Sampling Rate : 20.00K
[ydlidar_ros2_driver_node-5] [YDLIDAR] Now lidar is scanning...
[async_slam_toolbox_node-6] Registering sensor: [Custom Described Lidar]
[rviz2-3] [INFO] [1687230396.726792781] [rviz2]: Trying to create a map of size 253 x 97 using 1 swatches
[rviz2-3] [ERROR] [1687230396.822422349] [rviz2]: Vertex Program:rviz/glsl120/indexed_8bit_image.vert Fragment Program:rviz/glsl120/indexed_8bit_image.frag GLSL link result :
[rviz2-3] active samplers with a different type refer to the same texture image unit
[rviz2-3] [INFO] [1687230405.727756620] [rviz2]: Trying to create a map of size 254 x 103 using 1 swatches
[rviz2-3] [INFO] [1687230411.725638515] [rviz2]: Trying to create a map of size 254 x 148 using 1 swatches
[rviz2-3] [INFO] [1687230417.726750586] [rviz2]: Trying to create a map of size 261 x 157 using 1 swatches
```

#### Additional information
- Other than the change in LiDAR, everything else (odom publisher, tf) stays the same.
- Noticed robot jumps more during turns, not much jumping around when moving in a straight line.
- Since no problem occurs when using with RPLIDAR, it seems like its something caused by ydlidar_ros2_driver?
	-  Tried a different TG30, but the same issue occurs
- Could you please explain the potential issues or suggest how to identify them? thanks
