### ISSUE TITLE
Map not extending properly, new frames appear on top of each other

### ISSUE THREAD

**Issue by malthe-tb** [SteveMacenski/slam_toolbox#622]
- Operating System:
  - Ubuntu 20.04 
- Installation type:
  - Source
- ROS Version
  - ROS2 Foxy
- Version or commit hash:
  - 2.4.1-1focal.20230606.053256
- Laser unit:
  - Hokuyo 10LX 
  
#### Steps to reproduce issue
While using the slam_toolbox, I've observed an issue where, instead of the map being extended as I drive straight, new map frames seem to spawn on top of each other. The only configurations that have been modified are in the .yaml file as below:

```
slam_toolbox:
  ros__parameters:
    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping #localization
```

I launch slam_toolbox with the command:
```
ros2 launch slam_toolbox online_async_launch.py params_file:=/home/malthe/Repositories/localization_and_mapping/src/slam/config/slam_toolbox.yaml use_sim_time:=false
```

Driving straight for a couple of meters gives me the following output in rviz2:
![image](https://github.com/SteveMacenski/slam_toolbox/assets/60431464/39a46bcd-e449-4000-bd41-7882cced9c12)

#### Expected behavior
As the robot drives straight, the map should continuously extend to reflect the new areas explored by the robot.

#### Actual behavior
Instead of the map being extended, new map frames seem to spawn on top of each other, despite the robot moving in a straight line.

#### Additional information

I have tried to follow various tutorials and guides for setting up slam_toolbox, however, I have not been able to identify the part I'm getting wrong. Any assistance on this would be greatly appreciated. Please let me know if you need more information.
