### ISSUE TITLE
custom lidar source: wrong number of "expected range readings"

### ISSUE THREAD

**Issue by mibcat** [SteveMacenski/slam_toolbox#63]
Hi Steve,

I'm trying to use the software on a small home build diff drive robot. I'm using a X4 YDLIDAR and get the following message after starting the node:

```
process[slam_toolbox-1]: started with pid [14635]
[ INFO] [1566467601.227171238]: CeresSolver: Using SCHUR_JACOBI preconditioner.
[ INFO] [1566467601.227750066]: Using plugin solver_plugins::CeresSolver
Info: clipped range threshold to be within minimum and maximum range!
Registering sensor: [Custom Described Lidar]
LaserRangeScan contains 720 range readings, expected 721
```

In the default configuration the laser /scan topic has the following header:
```
> rostopic echo --noarr /scan -n 1
header: 
  seq: 4756
  stamp: 
    secs: 1566468140
    nsecs: 604043000
  frame_id: "base_laser_link"
angle_min: -3.14159274101
angle_max: 3.14159274101
angle_increment: 0.00872664619237
time_increment: 0.000164166660397
scan_time: 0.11819999665
range_min: 0.10000000149
range_max: 16.0
ranges: "<array type: float32, length: 720>"
intensities: "<array type: float32, length: 720>"
---
```

If changing the lidar parameters e.g. min/max angle the expected number of readings differs always by one ...

**Comment by SteveMacenski** [comment]
the 
> Info: clipped range threshold to be within minimum and maximum range!

isn't from my package, where is that from? Try running this without other things going. Is the issue you're reporting that or the scan return count?

**Comment by mibcat** [comment]
I refer to the message:
> LaserRangeScan contains 720 range readings, expected 721

But both messages are generated from the **karto_sdk** package which is included in your repo.
Therefore I thought this issue belongs to your code - sorry for not looking into the package.xml.

Nevertheless the issue is caused be the function LaserRangeFinder::Validate() in file **slam_toolbox/lib/karto_sdk/src/Karto.cpp** line 212

**Comment by SteveMacenski** [comment]
> Info: clipped range threshold to be within minimum and maximum range!
 
is not from my sdk. It looks like you're using http://docs.ros.org/jade/api/nav2d_karto/html/Sensor_8cpp_source.html which is unrelated to this. 

It looks like your laser scanner isn't correctly implementing its driver. Those min/max angles are inclusive. Its reporting 720 which is `[-pi, pi)` when the driver definition is `[-pi, pi]`. Try just changing the max_angle value from `pi` to `pi-angle_increment`. I've run this package on 5 different lidar models and haven't hit this problem before.

**Comment by mibcat** [comment]
> is not from my sdk. It looks like you're using http://docs.ros.org/jade/api/nav2d_karto/html/Sensor_8cpp_source.html which is unrelated to this.

This is confusing because my workspace only contains your repo and the lidar driver.
And the code of the output message can be found at:
https://github.com/SteveMacenski/slam_toolbox/blob/3816b4b022f06a14dbde90e3285cf24384009155/lib/karto_sdk/include/karto_sdk/Karto.h#L3998


I tried your hint by subtracting the `angle_increment` value from `max_angle` but than the driver gives me only 719 readings and the karto_sdk is complaining again about one missing reading.

Do you happen to know why a scan message must have exactly "n + 1" readings.
This means that the first and the last reading are identically.

I've never realized that the scan topic has an _unequal_ number of readings ... 
But the 5:1 ratio implies a driver adjustment ;-)

**Comment by SteveMacenski** [comment]
Huh that didnt show up in my search, apologies. These are some weird issues that are all from your laser message that I haven't run into before. 

The clipping error comes from reading the scans and taking the min and max ranges which _appear_ right from what you posted. 

```
range_min: 0.10000000149
range_max: 16.0
```

I don't know if its suspect or not that one of them has a bunch of sig figs and the other does not. Can you check the drivers and make sure those ranges are populated with the same datatype?

>  This means that the first and the last reading are identically.

That's not what that means. That happens to be a special case because you're using a 360 lidar, with another set its bounding the sample range `[N, M]`

**Comment by mibcat** [comment]
Yes, you are right: the 360 lidar is a special case and must be fixed in the driver.
Regarding the clipping error I will check the scan topic ...

**Comment by SteveMacenski** [comment]
If you have a really quick bag file (~30 seconds) of laser scans with your /tf /tf_static, I can also help debug on my side if its an issue with slam toolbox, but I suspect this is from the data. 

If you're modifying the drivers, try casting the numbers to doubles before populating the message, if you're using dynamic reconfigure its possible that is why the values look odd. 

In terms of the number of returns, because its "360" and not "359.999", I'd copy the first point to the end of the vector of points.

Here its just more important that the number of points in a scan is *consistent*, we could overload this so it'll just work but it seems like the lidar drivers should probably be updated for the next person

**Comment by mibcat** [comment]
While looking for reported issues of the lidar driver I realized that I used a "dead" repository which is not maintained anymore. Now after updating the driver the number of readings issue seems to be solved ;-))

The header of the scan topic has a slightly different `angle_increment` value (with full 360° setting):
```
> rostopic echo --noarr /scan -n 1
header: 
  seq: 113
  stamp: 
    secs: 1566508125
    nsecs: 152790560
  frame_id: "base_laser_link"
angle_min: -3.14159274101
angle_max: 3.14159274101
angle_increment: 0.00873878411949
time_increment: 0.00016411683464
scan_time: 0.118000000715
range_min: 0.10000000149
range_max: 16.0
ranges: "<array type: float32, length: 720>"
intensities: "<array type: float32, length: 720>"
---
```

But karto_sdk is now satisfied (I've added an additional output for verification)
```
process[slam_toolbox-1]: started with pid [3803]
[ INFO] [1566508140.586093886]: CeresSolver: Using SCHUR_JACOBI preconditioner.
[ INFO] [1566508140.586652694]: Using plugin solver_plugins::CeresSolver
Info: clipped range threshold to be within minimum and maximum range!
Registering sensor: [Custom Described Lidar]
Kgm: number of lidar readings provided 720
Kgm: number of lidar readings expected 720
 ```
Regarding the range clipping issure I've uploaded a short measurement of my test setup:
[ydlidar.zip](https://github.com/SteveMacenski/slam_toolbox/files/3531986/ydlidar.zip)

And thanks a lot for your support !!!

**Comment by SteveMacenski** [comment]
Can you check what the values of `math::Clip(rangeThreshold, GetMinimumRange(), GetMaximumRange())` are? the output, and each of the 3 things. Introspecting it might give you some ideas.

**Comment by mibcat** [comment]
Oh - I can see that the readings contains values with 0.0 !!!
Is this a correct behavior of the driver ?

```
header: 
  seq: 200
  stamp: 
    secs: 1566510128
    nsecs: 902494560
  frame_id: "base_laser_link"
angle_min: -3.14159274101
angle_max: 3.14159274101
angle_increment: 0.00873878411949
time_increment: 0.00016383867478
scan_time: 0.11779999733
range_min: 0.10000000149
range_max: 16.0
ranges: [1.5360000133514404, 1.5420000553131104, 1.5440000295639038, 0.0, 1.5440000295639038, 1.5360000133514404, 1.5240000486373901, 0.0, 0.0, 0.0, 1.559000015258789, 1.565999984741211, 0.0, 1.715999960899353, 0.0, 0.0, 0.0, 0.0, 1.7289999723434448, 1.7120000123977661, 0.0, 1.7200000286102295, 1.7209999561309814, 1.7280000448226929, 1.7039999961853027, 1.690000057220459, 0.0, 1.6920000314712524, 1.6970000267028809, 1.7020000219345093, 1.7059999704360962, 1.7130000591278076, 0.0, 1.718999981880188, 1.7230000495910645, 1.7289999723434448, 1.7359999418258667, 1.7419999837875366, 0.0, 1.7489999532699585, 1.75600004196167, 1.7640000581741333, 1.7719999551773071, 1.7799999713897705, 0.0, 1.7879999876022339, 1.7960000038146973, 1.8020000457763672, 1.8109999895095825, 1.8200000524520874, 1.8359999656677246,
...
```
