### ISSUE TITLE
Jumpings in Slamtoolbox output

### ISSUE THREAD

**Issue by oenzan** [SteveMacenski/slam_toolbox#664]
Using EKF we combine Imu and wheel odometry and give it to slamtoolbox as custom_odom. We also convert the baselink -> map tf from slamtoolbox to the odometry topic. Looking at the X and Y values, it shows 5-6 cm jumps, but custom_odom doesn't have these jumps. These jumps negatively affect the behavior of our controller. Slamtoolbox corrects the drift in the odometry but is there any way to smooth these corrections? 

We use foxy-devel version.
Ceres version 2.1.0
[my_bag6.zip](https://github.com/SteveMacenski/slam_toolbox/files/13998600/my_bag6.zip)

![Screenshot from 2024-01-20 18-49-12](https://github.com/SteveMacenski/slam_toolbox/assets/20473086/8a4eab42-6ca9-4fd2-ae51-7dd61efbed9a)

```
slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: custom_odom
    map_frame: map
    base_frame: base_footprint
    #scan_topic: /scan
    mode: mapping #localization

    # lifelong params
    lifelong_search_use_tree: false
    lifelong_minimum_score: 0.1
    lifelong_iou_match: 0.85
    lifelong_node_removal_score: 0.04
    lifelong_overlap_score_scale: 0.06
    lifelong_constraint_multiplier: 0.08
    lifelong_nearby_penalty: 0.001
    lifelong_candidates_scale: 0.03

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.01 
    map_update_interval: 2.2
    resolution: 0.05
    max_laser_range: 10.0
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000 
    enable_interactive_mode: true

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    
    minimum_travel_distance: 0.18 
    minimum_travel_heading: 0.8  
    
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.5
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 0.01
    loop_match_minimum_response_coarse: 2.0
    loop_match_minimum_response_fine: 3.0

    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.08
    correlation_search_space_resolution: 0.01 
    correlation_search_space_smear_deviation: 0.01

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03
    
    # Scan Matcher Parameters
    distance_variance_penalty: 0.11
    angle_variance_penalty: 0.47
    
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.35 
    coarse_angle_resolution: 0.0349
    minimum_distance_penalty: 0.4 
    minimum_angle_penalty: 0.41
    use_response_expansion: true
```
