### ISSUE TITLE
mapping failed (due to localization lost ?)

### ISSUE THREAD

**Issue by mibcat** [SteveMacenski/slam_toolbox#73]
Hi!
I'm running into trouble during the mapping mode: 
als long as the robot is moving straight forward or backward the mapping is fine but as soon as I add a rotation it seems that the localization gets more and more lost and therefore the mapping process will generate unusable maps.

I assume that I'm using a improper configuration and need some help ...

Here some information about the system:
- diff drive robot
- low cost YDLIDAR X4 
  - mounted upside (rotation of scan unit is clockwise)
  - usage of latest software version [V1.4.1](https://github.com/YDLIDAR/ydlidar_ros)
  - /scan topic header:
```
header: 
  seq: 192
  stamp: 
    secs: 1566986866
    nsecs:   8921560
  frame_id: "laser_link"
angle_min: -1.65806281567
angle_max: 1.65806281567
angle_increment: 0.00874967221171
time_increment: 0.00030976254493
scan_time: 0.117399998009
range_min: 0.10000000149
range_max: 16.0
ranges: "<array type: float32, length: 380>"
intensities: "<array type: float32, length: 380>"
---
```
- tf tree:
![tf_tree](https://user-images.githubusercontent.com/3083162/63846514-42830d00-c98c-11e9-8a86-5903f05833fb.png)
- scans seems to be valid related to distance and angle in relation to **laser_link**:
![rviz_tf_scan](https://user-images.githubusercontent.com/3083162/63847884-ff766900-c98e-11e9-8432-17ca8ed94837.png)

- using latest version of slam_toolbox (6281c8c04268d65386a2ba6f3cb1e7e8ff968555)
  - starting `roslaunch slam_toolbox online_sync.launch`
  - adjusting following parameters in **config/mapper_params_online_sync.yaml**:
    - base_frame: base_link
    - laser_frame: laser_link
    - max_laser_range: 16.0
  - running the node will give no error or warning messages:
```
process[sync_slam_toolbox_node-1]: started with pid [5404]
[ INFO] [1566983484.418758725]: Node using stack size 40000000
[ INFO] [1566983485.658208287]: CeresSolver: Using SCHUR_JACOBI preconditioner.
[ INFO] [1566983485.658327096]: Using plugin solver_plugins::CeresSolver
Registering sensor: [Custom Described Lidar]
[ INFO] [1566983491.127153328]: Creating 1 swatches
```
