### ISSUE TITLE
Setting "use_scan_matching" to "false" leads to an error

### ISSUE THREAD

**Issue by harixx2011** [SteveMacenski/slam_toolbox#774]
**Required Info:**

- Operating System:
  - Ubuntu 24.04.2 LTS
- Installation type:
- ROS Version
  - ROS2 Jazzy
- Version or commit hash:
  - 2.8.3-1
  
#### Steps to reproduce issue
Start slam:
`ros2 launch slam_toolbox localization_launch.py slam_params_file:=slam_toolbox_configs/slam_toolbox_edited.yaml use_sim_time:=true`

In a second terminal start playing of bag:
`ros2 bag play /path/to/bag --clock 100 -r 5.0`

#### Expected behavior
Normal playing of bag, with SLAM Node active for localization.

#### Actual behavior
A short time after playing the bag, slam toolbox ends with an error:
`[ERROR] [localization_slam_toolbox_node-1]: process has died [pid 22777, exit code -11, cmd '/opt/ros/jazzy/lib/slam_toolbox/localization_slam_toolbox_node --ros-args -r __node:=slam_toolbox -r __ns:=/ --params-file /slam_toolbox_configs/slam_toolbox_edited.yaml --params-file /tmp/launch_params_n8gxpxoa']
`

#### Additional information
mapper_params_localization.yaml and log file:

```
slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: HuberLoss

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    mode: localization # mapping

    # if you'd like to start localizing on bringup in a map and pose
    map_file_name: /path/to/slam_toolbox_graph
    map_start_pose: [0.0, 0.0, 0.0]

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02 #if 0 never publishes odometry
    map_update_interval: 5.0
    resolution: 0.05
    min_laser_range: 0.0 #for rastering images
    max_laser_range: 20.0 #for rastering images
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000 #// program needs a larger stack size to serialize large maps (X)

    # General Parameters
    use_scan_matching: false
    use_scan_barycenter: true
    minimum_travel_distance: 0.25
    minimum_travel_heading: 0.25
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    do_loop_closing: true
    loop_match_minimum_chain_size: 3
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03
    loop_search_maximum_distance: 3.0

    # Scan Matcher Parameters
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0

    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: false
    min_pass_through: 2
    occupancy_threshold: 0.1
```

```
1748002593.1965303 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.IncludeLaunchDescription'
1748002593.1970634 [INFO] [launch]: All log files can be found below /home/.ros/log/2025-05-23-14-16-33-196136-PF3HXMFV-25194
1748002593.1971219 [INFO] [launch]: Default logging verbosity is set to DEBUG
1748002593.2057760 [DEBUG] [launch]: processing event: '<launch.events.include_launch_description.IncludeLaunchDescription object at 0x7bc891710ad0>'
1748002593.2058544 [DEBUG] [launch]: processing event: '<launch.events.include_launch_description.IncludeLaunchDescription object at 0x7bc891710ad0>' ✓ '<launch.event_handlers.on_include_launch_description.OnIncludeLaunchDescription object at 0x7bc891711a90>'
1748002593.3507855 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch_ros.events.lifecycle.ChangeState'
1748002593.3605363 [DEBUG] [launch]: processing event: '<launch_ros.events.lifecycle.change_state.ChangeState object at 0x7bc89107fb90>'
1748002593.3606751 [DEBUG] [launch]: processing event: '<launch_ros.events.lifecycle.change_state.ChangeState object at 0x7bc89107fb90>' ✓ '<launch.event_handler.EventHandler object at 0x7bc87f70d940>'
1748002593.3629539 [INFO] [localization_slam_toolbox_node-1]: process started with pid [25207]
1748002593.3630824 [DEBUG] [launch.launch_context]: emitting event: 'launch.events.process.ProcessStarted'
1748002593.3632078 [DEBUG] [launch]: processing event: '<launch.events.process.process_started.ProcessStarted object at 0x7bc8911da660>'
1748002593.3772089 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.process.ProcessStderr'
1748002593.3774371 [DEBUG] [launch]: processing event: '<launch.events.process.process_stderr.ProcessStderr object at 0x7bc8900a38c0>'
1748002593.3774941 [DEBUG] [launch]: processing event: '<launch.events.process.process_stderr.ProcessStderr object at 0x7bc8900a38c0>' ✓ '<launch.event_handlers.on_process_io.OnProcessIO object at 0x7bc87f795ca0>'
1748002593.3841662 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.process.ProcessStderr'
1748002593.3843157 [DEBUG] [launch]: processing event: '<launch.events.process.process_stderr.ProcessStderr object at 0x7bc890317ce0>'
1748002593.3843658 [DEBUG] [launch]: processing event: '<launch.events.process.process_stderr.ProcessStderr object at 0x7bc890317ce0>' ✓ '<launch.event_handlers.on_process_io.OnProcessIO object at 0x7bc87f795ca0>'
1748002593.6131432 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch_ros.events.lifecycle.StateTransition'
1748002593.6141715 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.process.ProcessStderr'
1748002593.6208868 [DEBUG] [launch]: processing event: '<launch_ros.events.lifecycle.state_transition.StateTransition object at 0x7bc87f796750>'
1748002593.6223931 [DEBUG] [launch]: processing event: '<launch.events.process.process_stderr.ProcessStderr object at 0x7bc89064e720>'
1748002593.6226327 [DEBUG] [launch]: processing event: '<launch.events.process.process_stderr.ProcessStderr object at 0x7bc89064e720>' ✓ '<launch.event_handlers.on_process_io.OnProcessIO object at 0x7bc87f795ca0>'
1748002593.6244662 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.process.ProcessStderr'
1748002593.6250656 [DEBUG] [launch]: processing event: '<launch.events.process.process_stderr.ProcessStderr object at 0x7bc8881fac00>'
1748002593.6252918 [DEBUG] [launch]: processing event: '<launch.events.process.process_stderr.ProcessStderr object at 0x7bc8881fac00>' ✓ '<launch.event_handlers.on_process_io.OnProcessIO object at 0x7bc87f795ca0>'
1748002593.6258376 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.process.ProcessStderr'
1748002593.6269405 [DEBUG] [launch]: processing event: '<launch.events.process.process_stderr.ProcessStderr object at 0x7bc8881fac00>'
1748002593.6271627 [DEBUG] [launch]: processing event: '<launch.events.process.process_stderr.ProcessStderr object at 0x7bc8881fac00>' ✓ '<launch.event_handlers.on_process_io.OnProcessIO object at 0x7bc87f795ca0>'
1748002593.8533134 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.process.ProcessStdout'
1748002593.8536599 [DEBUG] [launch]: processing event: '<launch.events.process.process_stdout.ProcessStdout object at 0x7bc890317ce0>'
1748002593.8537483 [DEBUG] [launch]: processing event: '<launch.events.process.process_stdout.ProcessStdout object at 0x7bc890317ce0>' ✓ '<launch.event_handlers.on_process_io.OnProcessIO object at 0x7bc87f795ca0>'
1748002593.8544431 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.process.ProcessStderr'
1748002593.8547950 [DEBUG] [launch]: processing event: '<launch.events.process.process_stderr.ProcessStderr object at 0x7bc89064e720>'
1748002593.8548574 [DEBUG] [launch]: processing event: '<launch.events.process.process_stderr.ProcessStderr object at 0x7bc89064e720>' ✓ '<launch.event_handlers.on_process_io.OnProcessIO object at 0x7bc87f795ca0>'
1748002593.8615668 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch_ros.events.lifecycle.StateTransition'
1748002593.8621755 [DEBUG] [launch]: processing event: '<launch_ros.events.lifecycle.state_transition.StateTransition object at 0x7bc87f70d820>'
1748002593.8622344 [DEBUG] [launch]: processing event: '<launch_ros.events.lifecycle.state_transition.StateTransition object at 0x7bc87f70d820>' ✓ '<launch_ros.event_handlers.on_state_transition.OnStateTransition object at 0x7bc89106b470>'
1748002593.8622909 [INFO] [launch.user]: [LifecycleLaunch] Slamtoolbox node is activating.
1748002593.8623433 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch_ros.events.lifecycle.ChangeState'
1748002593.8626268 [DEBUG] [launch]: processing event: '<launch_ros.events.lifecycle.change_state.ChangeState object at 0x7bc89106bbf0>'
1748002593.8626711 [DEBUG] [launch]: processing event: '<launch_ros.events.lifecycle.change_state.ChangeState object at 0x7bc89106bbf0>' ✓ '<launch.event_handler.EventHandler object at 0x7bc87f70d940>'
1748002593.8632960 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch_ros.events.lifecycle.StateTransition'
1748002593.8637445 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.process.ProcessStderr'
1748002593.8638093 [DEBUG] [launch]: processing event: '<launch_ros.events.lifecycle.state_transition.StateTransition object at 0x7bc87f796750>'
1748002593.8641312 [DEBUG] [launch]: processing event: '<launch.events.process.process_stderr.ProcessStderr object at 0x7bc8900a38c0>'
1748002593.8641856 [DEBUG] [launch]: processing event: '<launch.events.process.process_stderr.ProcessStderr object at 0x7bc8900a38c0>' ✓ '<launch.event_handlers.on_process_io.OnProcessIO object at 0x7bc87f795ca0>'
1748002593.8651230 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch_ros.events.lifecycle.StateTransition'
1748002593.8656511 [DEBUG] [launch]: processing event: '<launch_ros.events.lifecycle.state_transition.StateTransition object at 0x7bc87f794290>'
1748002598.3773887 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.process.ProcessStdout'
1748002598.3777945 [DEBUG] [launch]: processing event: '<launch.events.process.process_stdout.ProcessStdout object at 0x7bc891153080>'
1748002598.3779624 [DEBUG] [launch]: processing event: '<launch.events.process.process_stdout.ProcessStdout object at 0x7bc891153080>' ✓ '<launch.event_handlers.on_process_io.OnProcessIO object at 0x7bc87f795ca0>'
1748002605.1064014 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.process.ProcessStderr'
1748002605.1068408 [DEBUG] [launch]: processing event: '<launch.events.process.process_stderr.ProcessStderr object at 0x7bc891153080>'
1748002605.1070192 [DEBUG] [launch]: processing event: '<launch.events.process.process_stderr.ProcessStderr object at 0x7bc891153080>' ✓ '<launch.event_handlers.on_process_io.OnProcessIO object at 0x7bc87f795ca0>'
1748002605.1093173 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.process.ProcessStdout'
1748002605.1096716 [DEBUG] [launch]: processing event: '<launch.events.process.process_stdout.ProcessStdout object at 0x7bc89064e720>'
1748002605.1098022 [DEBUG] [launch]: processing event: '<launch.events.process.process_stdout.ProcessStdout object at 0x7bc89064e720>' ✓ '<launch.event_handlers.on_process_io.OnProcessIO object at 0x7bc87f795ca0>'
1748002606.2006752 [DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.process.ProcessStderr'
1748002606.2010982 [DEBUG] [launch]: processing event: '<launch.events.process.process_stderr.ProcessStderr object at 0x7bc89013c620>'
1748002606.2012382 [DEBUG] [launch]: processing event: '<launch.events.process.process_stderr.ProcessStderr object at 0x7bc89013c620>' ✓ '<launch.event_handlers.on_process_io.OnProcessIO object at 0x7bc87f795ca0>'
1748002609.9775801 [ERROR] [localization_slam_toolbox_node-1]: process has died [pid 25207, exit code -11, cmd '/opt/ros/jazzy/lib/slam_toolbox/localization_slam_toolbox_node --ros-args -r __node:=slam_toolbox -r __ns:=/ --params-file /slam_toolbox_configs/slam_toolbox_edited.yaml --params-file /tmp/launch_params_lo775ute'].
1748002609.9777243 [DEBUG] [launch.launch_context]: emitting event: 'launch.events.process.ProcessExited'
1748002609.9779699 [DEBUG] [launch]: processing event: '<launch.events.process.process_exited.ProcessExited object at 0x7bc8912a73e0>'
1748002609.9780505 [DEBUG] [launch]: processing event: '<launch.events.process.process_exited.ProcessExited object at 0x7bc8912a73e0>' ✓ '<launch.event_handlers.on_process_exit.OnProcessExit object at 0x7bc87f795e50>'
1748002609.9781289 [DEBUG] [launch]: processing event: '<launch.events.process.process_exited.ProcessExited object at 0x7bc8912a73e0>' ✓ '<launch.event_handlers.on_process_exit.OnProcessExit object at 0x7bc87f795cd0>'
1748002609.9784002 [DEBUG] [launch.launch_context]: emitting event: 'launch.events.Shutdown'
1748002609.9787230 [DEBUG] [launch]: processing event: '<launch.events.shutdown.Shutdown object at 0x7bc89106b980>'
1748002609.9788001 [DEBUG] [launch]: processing event: '<launch.events.shutdown.Shutdown object at 0x7bc89106b980>' ✓ '<launch.event_handlers.on_shutdown.OnShutdown object at 0x7bc87f70de80>'
1748002609.9789026 [DEBUG] [launch]: processing event: '<launch.events.shutdown.Shutdown object at 0x7bc89106b980>' ✓ '<launch.event_handlers.on_shutdown.OnShutdown object at 0x7bc89113b9e0>'
1748002611.4866967 [DEBUG] [launch]: processing event: '<launch.events.shutdown.Shutdown object at 0x7bc89106b980>' ✓ '<launch.event_handlers.on_shutdown.OnShutdown object at 0x7bc8916810d0>'
```
