### ISSUE TITLE
debug_logging: true doesn't seem to log anything extra

### ISSUE THREAD

**Issue by bentwookie** [SteveMacenski/slam_toolbox#785]
**Required Info:**

- Operating System:
Debian GNU/Linux 12 (bookworm) (on a pi 5)

- Installation type:
Binary

- ROS Version
 Humble

- Version or commit hash:
Package: ros-humble-slam-toolbox
Version: 2.6.10-1jammy.20250614.094833

- Laser unit:
rplidar c1

  
#### Steps to reproduce issue
I'm trying to debug why slam_toolbox (online_async) generates a map once, and then doesn't update when my robot hardware moves. In order to do that, I enabled debug_logging in my yaml params. I've verified via `ros2 param get slam_toolbox debug_logging` that it's set. However, I don't see any extra logging beyond INFO. 

#### Expected behavior
I was hoping to see some logging responding to my /scan messages that indicated what it was or wasn't doing.

#### Actual behavior
I don't see anything beyond normal (to me) looking INFO logs. 

#### Additional information
I can write up a separate issue for why things aren't updating, but I wanted to come loaded with more information first :)

my parameter file looks like so:
```
slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    mode: mapping #localization

    # if you'd like to immediately start continuing a map at a given pose
    # or at the dock, but they are mutually exclusive, if pose is given
    # will use pose
    #map_file_name: test_steve
    # map_start_pose: [0.0, 0.0, 0.0]
    #map_start_at_dock: true

    debug_logging: true
    throttle_scans: 1
    transform_publish_period: 0.02 #if 0 never publishes odometry
    map_update_interval: 5.0
    resolution: 0.05
    min_laser_range: 0.1 #for rastering images
    max_laser_range: 16.0 #for rastering images
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000 #// program needs a larger stack size to serialize large maps
    enable_interactive_mode: true

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1  
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true 
    loop_match_minimum_chain_size: 10           
    loop_match_maximum_variance_coarse: 3.0  
    loop_match_minimum_response_coarse: 0.35    
    loop_match_minimum_response_fine: 0.45

    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1 

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 0.5      
    angle_variance_penalty: 1.0    

    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0349        
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
    min_pass_through: 2
    occupancy_threshold: 0.1
```
